### ISSUE TITLE
Class-Skeleton.php A non-numeric value encountered

### ISSUE THREAD

**Issue by C3realGuy** [Wedge/wedge#57] opened 2017-02-28 15:02 UTC
```
index.php?action=profile;area=notifications;sa=posts 
Warning (level 2): A non-numeric value encountered 
Filter einschalten: Nur Fehler von dieser Datei anzeigen Datei: /***/gz/app/Class-Skeleton.php
Zeile: 175
```

**Comment by Nao** [comment] 2017-03-01 16:05
I'm sorry, I'm really stumped by this one... Can't reproduce it. And the line of code doesn't make sense, it only manipulates a forced boolean.

**Comment by C3realGuy** [comment] 2017-03-02 11:24
For me the error pops up every time i access the url.

Wedge says it has something to do with this line.
```$result &= $this->remove($target);```

Wedge version is ~3 commits behind master. Will look into
it as soon as find time. Next week on friday i'm done with my next
exam and will hopefully have some more time.

**Comment by Nao** [comment] 2017-03-02 11:33
That's the same line for me (I haven't touched this file in months, as it's working as expected... ^^)
Just trace through the code, you'll notice that both functions always return a boolean value.
Or is PHP 7.1 that not even supports booleans in logic tests..?!?!

Try to replace that code block with:

		if (isset($this->layers[$target]))
			$result = (bool) $this->insert_layer($new_name, $target, 'rename') & (bool) $this->remove_layer($target);
		else
			$result = (bool) $this->before($target, $new_name) & (bool) $this->remove($target);

(Or just insert (bool) before the $this calls, that's really the only change.)

**Comment by Nao** [comment] 2017-03-02 11:36
Oh... Bugger. The problem wasn't with remove() but before(). In some situations it can return a non-boolean.
I'd need to find out what's going on with that. I'll check.

**Comment by Nao** [comment] 2017-03-02 11:48
Okay I committed something, should be good enough, and the least likely to break something else. ;)
remove() calls op() with in turns returns false on error, and $to (i.e. the original layer name) on success, instead of true. PHP 7.0 and before were fine because a boolean & on a non-empty, non-'0' string would cast it as 'true'.

I guess this change in PHP 7.1 is a good thing... But like many other things, should have happened years ago. ;)

**Comment by Nao** [comment] 2017-04-14 20:05
(Fixed!)

**Closed by Nao** 2017-04-14 20:05 UTC
